title: mecaproject
description: Manycore Operating System related researches

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

defaults:
  - scope:
      path: "Data/image/00"
    values:
      image: true
      
  - scope:
      path: "Data/image/01"
    values:
      image: true
  
  - scope:
      path: "Data/image/02"
    values:
      image: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
